### PR TITLE
[Docs] Move to ReadTheDocs

### LINKED ISSUE #11: Shift the docs to readthedocs
It would be great if we shift the README.md to readthedocs, it will be really nice for new contributors as they can make the offline copy for themselves 

labels can be added like:-  Hacktoberfest

P.S.- I'm working on this :smile:

### PR DESCRIPTION
**Pull request by DaffyTheDuck**
* Moved the documentation to ReadTheDocs
* Edited README.md

Closes #11

### CODE REVIEW

**Comment by DaffyTheDuck** [comment]
Okay, let me fix the conflicts, then you can merge it @andrefpoliveira :smile:

**Comment by DaffyTheDuck** [comment]
And may I know what changes you've made recently ? means functions and other things?

**Comment by andrefpoliveira** [comment]
@DaffyTheDuck you can submit with the info you have :) I will update later

**Comment by andrefpoliveira** [comment]
@DaffyTheDuck tell me when you are ready

**Comment by DaffyTheDuck** [comment]
Fixed the conflict, but I think you need to squash the commits :smile_cat:

**Comment by DaffyTheDuck** [comment]
And about the logo, I was trying to resize it but it was looking same as before :sweat_smile: 
I'll try to improve it, once you approve :smile_cat:

**Comment by andrefpoliveira** [comment]
@DaffyTheDuck thanks for your help!

**Pull request merged**
