### PR TITLE
Add new examples

### PR DESCRIPTION
**Pull request by UjwalKandi**
Issue #5 :  Added 7 new examples.

### CODE REVIEW

**Comment by andrefpoliveira** [comment]
@UjwalKandi first of all thanks for contributing! As you can see, there is a check failing. The reason for that is the fact that the pansy file inside the LargestAmongThree folder is not named code.pansy. If you could fix that, it would be great! :)

**Comment by andrefpoliveira** [comment]
@UjwalKandi Ok I think this would be the last problem. You added comments to the output.txt of the CelsiusToFahrenheit folder. Please remove those and it should be fine

**Comment by UjwalKandi** [comment]
> @UjwalKandi first of all thanks for contributing! As you can see, there is a check failing. The reason for that is the fact that the pansy file inside the LargestAmongThree folder is not named code.pansy. If you could fix that, it would be great! :)

Hello @andrefpoliveira, I have renamed the .pansy file to *code.pansy*. And have also updated my fork repo. Yet it still shows a failed check. Is it because I made some changes to the **examples / README.md** file?

**Comment by UjwalKandi** [comment]
> @UjwalKandi Ok I think this would be the last problem. You added comments to the output.txt of the CelsiusToFahrenheit folder. Please remove those and it should be fine

Oh okay 👍

**Comment by UjwalKandi** [comment]
Hey @andrefpoliveira , 
Can you add the **_hacktoberfest-accepted_** label to this PR?
Labelling a pull request ‘hacktoberfest-accepted’, will be helpful to qualify.

**Comment by andrefpoliveira** [comment]
@UjwalKandi being merged is enough but sure :)

**Pull request merged**
